### PR TITLE
Adding palindrome

### LINKED ISSUE #14: Write a code to print Palindrome
Create a file of your name and submit a PR.

### PR DESCRIPTION
**Pull request by Noburu-Hasashi**
As you requested, I've added a function for palindrome. If you want any changes, let me know.
Fixes #14

### CODE REVIEW

**Comment by aditya08maker** [comment]
@Noburu-Hasashi 
Merged your PR, it will count as a valid submission in the Hacktoberfest

**Comment by Noburu-Hasashi** [comment]
The PR does show up on hacktoberfest website, but it's showing a clock face, and it says "In progress: 1"
Can you tag "hacktoberfest-accepted" to my pull request please?

**Comment by aditya08maker** [comment]
It's the same, every PR has a cooldown period of 14 days, I've accepted it,
automatically after 14 days it will enable the milestone.

**Comment by Noburu-Hasashi** [comment]
Oh okay, got it. Thanks Aditya.

**Pull request merged**
